/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Color;
import java.awt.Label;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author thipu
 */
public class  news extends javax.swing.JFrame {

    public JPanel getSettings() {
        return settings;
    }

    public JPanel getNotifi() {
        return notifi;
    }

    public JPanel getLogout() {
        return Logout;
    }

    public JPanel getPic() {
        return pic;
    }

    
    /**
     * Creates new form news
     */
    public news() {
        initComponents();
        settings.setVisible(false);
        notifi.setVisible(false);
        Logout.setVisible(false);
        pic.setVisible(false);
        settings.putClientProperty(FlatClientProperties.STYLE, "arc: 999");
        notifi.putClientProperty(FlatClientProperties.STYLE, "arc: 999");
        Logout.putClientProperty(FlatClientProperties.STYLE, "arc: 999");
        Logout.putClientProperty(FlatClientProperties.STYLE, "arc: 999");
        pic.putClientProperty(FlatClientProperties.STYLE, "arc: 999");
        jPanel1.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.0f));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        settings = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        notifi = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        pic = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new Color(0.0f, 0.0f, 0.0f, 0.1f));

        settings.setBackground(new java.awt.Color(119, 82, 254));
        settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Settings");
        settings.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 9, -1, -1));

        Logout.setBackground(new java.awt.Color(119, 82, 254));
        Logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Logout");
        Logout.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 10, -1, -1));

        notifi.setBackground(new java.awt.Color(119, 82, 254));
        notifi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Notifications");
        notifi.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, -1, -1));

        pic.setBackground(new java.awt.Color(119, 82, 254));
        pic.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Sylfaen", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Profile");
        pic.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 10, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(notifi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111)
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notifi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UIManager.put("ToggleButton.selectedBackground", new Color(170, 87, 254));
        UIManager.put("ToggleButton.hoverBackground", new Color(95, 186, 255));
        UIManager.put("ToggleButton.selectedForeground", new Color(255, 255, 255));
        UIManager.put("ToggleButton.pressedBackground", new Color(27, 155, 255));
        UIManager.put("Button.arc", 999);
        UIManager.put("Button.boldText", true);
        UIManager.put("Button.borderWidth", 0);
        UIManager.put("TextComponent.arc", 999);
        UIManager.put("Component.focusWidth", 0);
        UIManager.put("ScrollBar.thumbArc", 999);
        UIManager.put("ScrollBar.width", 8);
        UIManager.put("ScrollBar.borderWidth", 0);
        UIManager.put("ScrollBar.hoverThumbColor", new Color(153, 51, 255));//[153,51,255]

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new news().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Logout;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel21;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel notifi;
    public javax.swing.JPanel pic;
    public javax.swing.JPanel settings;
    // End of variables declaration//GEN-END:variables
}
